### ISSUE TITLE
Allow TimeoutError to have 504 statusCode

### ISSUE THREAD

**Issue by jdmoody** [drcallaway/apollo-link-timeout#24]
I think the [408 HTTP code](https://tools.ietf.org/html/rfc2068#section-10.4.9) is usually used when the client takes too long to send a request to the server:
>   The client did not produce a request within the time that the server
   was prepared to wait. The client MAY repeat the request without
   modifications at any later time.

I think a [504](https://tools.ietf.org/html/rfc2068#section-10.5.5) may be more accurate for this error because it is the server that has failed to send a response to the client:
>    The server, while acting as a gateway or proxy, did not receive a
   timely response from the upstream server it accessed in attempting to
   complete the request.

This is especially accurate for my use-case where I'm using this link for SSR, so I have a server acting as a proxy that will eventually return a 504 to the client.

---

I'm happy to make a PR for this, I just wanted to sanity-check my understanding 😊 

I was planning on adding an additional `statusCode` parameter to the `TimeoutLink` constructor that is used to set the underlying `TimeoutError`'s `statusCode`. (I would default the link's statusCode to a 408 to maintain backwards-compatibility)

**Comment by drcallaway** [comment]
Thanks for pointing this out. It does appear that the 408 is meant to be returned when the server times out waiting for the client request. I suppose that the 504 is more accurate (though in this case it may or may not be due to the server waiting on a response from an upstream server). My only concern with modifying the default is that some clients are likely already expecting a 408. Perhaps it would be better to update the link to accept an optional `timeoutStatusCode` value that would be passed to the TimeoutError's constructor in order to override the default 408. What do you think?

**Comment by drcallaway** [comment]
Thanks for pointing this out. It does appear that the 408 is meant to be returned when the server times out waiting for the client request. I suppose that the 504 is more accurate (though in this case it may or may not be due to the server waiting on a response from an upstream server). I think your idea about adding a `statusCode` param to override the default sounds great. If you don't mind, please go ahead with a PR.

Thanks!
