### ISSUE TITLE
`controller` is not a valid fetch option

### ISSUE THREAD

**Issue by jaydenseric** [drcallaway/apollo-link-timeout#26]
As far as I can tell looking at MDN docs, etc. `signal` is a valid fetch option, but `controller` is not:

https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch#Parameters

The code here uses `controller` instead of `signal` when interacting with fetch options:

https://github.com/drcallaway/apollo-link-timeout/blob/69bca909ce97ab8ae8190560714a83b99b132088/src/timeoutLink.ts#L29

I haven't tested this link out, so I don't know exactly what will happen, but it looks like there would be bugs due to this.

**Comment by drcallaway** [comment]
That's true but the code isn't expecting Fetch to act on that option. Rather, the option is used only in the timeout link:
<pre>
      let fetchOptions = context.fetchOptions || {};
      controller = fetchOptions.controller || new AbortController();
</pre>
If the client adds a controller to the fetchOptions object then that controller will be used by the timeout link (not by Fetch). I suppose that it would have been better to have the client add the controller to the context directly rather than to the fetchOptions object but I don't see any harm in it since it will be ignored by Fetch.
